# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Pod release"
  lane :release_pod do
    # sh("podspec_generator.sh")
    version_number = get_version_number(
      xcodeproj: "FGCKitSampleApp.xcodeproj",
      target: "FGCKitSampleApp"
    )
    # Extracting biuld number from relevant plist - this is due to multitarget project
    build_number = get_info_plist_value(path: "./FGCKitSampleApp/Info.plist", key: "CFBundleVersion")
    # inc current build number
    build_number = build_number.to_i + 1
    build_number = build_number.to_s
    update_info_plist(
      plist_path:"./FGCKitSampleApp/Info.plist",
      block: lambda { |plist|  
        plist["CFBundleVersion"] = build_number
      }
    )
    version = version_number+"."+build_number
    sh "python release_pod.py "+version
  end

end
